export const beers = [
    {
        id:'pbrTall',
        name: 'Pabst Blue Ribbon',
        description: 'ABV: 4.8 crisp classic lager',
        image: 'pbr.jpg',
        price: 2,
        category: 'lager',
    },
    {
        id:'805tall',
        name: '805',
        description: 'Blonde Ale',
        image: 'pbr.jpg',
        price: 3,
        category: 'blonde',
    },
    {
        id:'bastardTall',
        name: 'Arrogant Bastard',
        description: 'Strong IPA',
        image: 'pbr.jpg',
        price: 6,
        category: 'IPA',
    },
    {
        id:'rainierTall',
        name: 'Rainier',
        description: 'Light lager',
        image: 'pbr.jpg',
        price: 2,
        category: 'lager',
    },
    {
        id: 'easyJackTall',
        name: 'Easy Jack',
        description: 'Classic IPA',
        image: 'pbr.jpg',
        price: 4,
        category: 'IPA',
    },
];
